trivial: Fix off-by-1-error in mempool_tests
This led to rare but sporadic false failures in this unit test leading
to this error message:

```
error: in "mempool_tests/DisconnectPoolAddForBlock": check tinyPool.DynamicMemoryUsage() < 100'000 has failed [100000 >= 100000]
```

The reason was the check should be for less-than-or-equal-to (not
less-than).