trivial refactor: Remove spurious virtual from final ~CZMQNotificationInterface
Co-authored-by: Calin Culianu <calin.culianu@gmail.com>

Backport of Core#32187

Original commiter message:

    virtual does not make sense here, because:

    The class is final, thus the destructor isn't overridden in a derived class
    The destructor also isn't overriding the destructor of the base, clarified in commit 2b3ea39
    Clang 21 may warn about this
    src/zmq/zmqnotificationinterface.h:25:13: error: virtual method '~CZMQNotificationInterface' is inside a 'final' class and can never be overridden [-Werror,-Wunnecessary-virtual-specifier]
       25 |     virtual ~CZMQNotificationInterface();
          |             ^
    Fix all issues by removing it.

Also in this commit: Small nits -- default initialize pcontext, make
default c'tor = default, move #include <map> to .cpp file since it
doesn't need to live in the header.